# Generated by Django 3.0.6 on 2020-08-01 12:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('initialprice', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('available', models.BooleanField()),
                ('start_interval', models.TimeField()),
                ('end_interval', models.TimeField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(default='user', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sold_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Item')),
                ('user_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.User')),
            ],
        ),
        migrations.CreateModel(
            name='Open_Bidding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=10)),
                ('from_user', models.CharField(max_length=100)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.User')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.User'),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('bid_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Item')),
                ('user_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.User')),
            ],
        ),
    ]
